# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sentei < Formula
  desc "A TUI tool for cleaning up stale git worktrees"
  homepage "https://github.com/bonboncinnabon/sentei"
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bonboncinnabon/sentei/releases/download/v1.14.0/sentei_1.14.0_darwin_amd64.tar.gz"
      sha256 "ff1751a33f16e66458f96ad2f876207696da8401bfc953da6f0b413968509a5f"

      define_method(:install) do
        bin.install "sentei"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bonboncinnabon/sentei/releases/download/v1.14.0/sentei_1.14.0_darwin_arm64.tar.gz"
      sha256 "7845c377099e7d6e8a95ae204b9a401f70fd8d79718818b6523196d1b37a705b"

      define_method(:install) do
        bin.install "sentei"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bonboncinnabon/sentei/releases/download/v1.14.0/sentei_1.14.0_linux_amd64.tar.gz"
      sha256 "cbbbd5be8b8273940c97bbfcc4bf7bee58d87c86960e8db131763a06a981e374"
      define_method(:install) do
        bin.install "sentei"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bonboncinnabon/sentei/releases/download/v1.14.0/sentei_1.14.0_linux_arm64.tar.gz"
      sha256 "ab7113265de7bf7d36675a5bae77ced52298cfdb60ef35b24230ece10b04ec94"
      define_method(:install) do
        bin.install "sentei"
      end
    end
  end
end
